version: '3.7'

services:
  weather-api:
    build: 
      context: WebApi
      dockerfile: Dockerfile
    container_name: weather-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - CTELEPORT_WEATHER_API_Redis:ConnectionString=redis:6379
      - CTELEPORT_WEATHER_API_WeatherHttpClientConfiguration:BaseUrl=https://api.openweathermap.org/
      - CTELEPORT_WEATHER_API_WeatherHttpClientConfiguration:ApiKey=YOUR_API_KEY
      - CTELEPORT_WEATHER_API_WeatherHttpClientConfiguration:MaxResponseContentBufferSize=3000
    ports:
      - "5944:8080"
    depends_on:
      - redis
    networks:
      - weather-api-network

networks:
  weather-api-network:
    driver: bridge